name: CI
on:
  push:
    branches: [ 'proposals/3905-case-for-windows-only' ]
    tags: [ '*.*.*' ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
        os: [ windows-latest]
        # Just to slim down the test matrix:
        exclude:
          - python-version: '3.9'
            os: macos-latest
          - python-version: '3.9'
            os: windows-latest
          - python-version: '3.10'
            os: ubuntu-latest
          - python-version: '3.11'
            os: macos-latest
          - python-version: '3.11'
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: |
          python -m pip install --upgrade hatch
      - name: Install dependencies
        run: |
          pip3 install .
      - name: Run tests
        run: |
          python -m unittest mkdocs.tests.shutdown_by_signal_tests.Shutdown_by_signal_tests
